############################
#  這是正式用的環境設定        #
############################

# Server config
server.port: 3000
server.host: "0.0.0.0"
server.mode: development

# Database config
db.port: 5432
db.host: "172.28.112.1"
db.user: postgres
db.password: mysecretpassword
db.name: postgres

# Swagger config
swagger.enabled: true
swagger.host: "<public_ip>"