############################
#  這是測試用的環境設定        #
############################

# Server config
server.port: 81
server.host: localhost
server.mode: development

# Database config
db.port: 5433
db.host: localhost
db.user: postgres
db.password: mysecretpassword
db.name: postgres
